//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emp_PayRoll_ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressBookTable
    {
        public int personId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<long> zipCode { get; set; }
        public Nullable<long> phoneNumber { get; set; }
        public string email { get; set; }
        public string bookType { get; set; }
    }
}
