//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emp_PayRoll_ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRollTable
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public string gender { get; set; }
        public Nullable<long> phonenumber { get; set; }
        public string address { get; set; }
        public string department { get; set; }
        public Nullable<int> BasicPay { get; set; }
        public Nullable<double> Deduction { get; set; }
        public Nullable<double> TaxablePay { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> NetPay { get; set; }
    }
}
